version: '3'

services:
  producer:
    build:
      context: ./producer
    ports:
      - "8000:8000"
    depends_on:
      - database
    networks:
      - inventory_network

  consumer_one:
    build:
      context: ./consumer_one
    depends_on:
      - rabbitmq
      - database
    networks:
      - inventory_network

  consumer_two:
    build:
      context: ./consumer_two
    depends_on:
      - rabbitmq
      - database
    networks:
      - inventory_network

  consumer_three:
    build:
      context: ./consumer_three
    depends_on:
      - rabbitmq
      - database
    networks:
      - inventory_network

  consumer_four:
    build:
      context: ./consumer_four
    depends_on:
      - rabbitmq
      - database
    networks:
      - inventory_network
      
  consumer_five:
    build:
      context: ./consumer_five
    depends_on:
      - rabbitmq
      - database
    networks:
      - inventory_network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - inventory_network

  database:
    build:
      context: ./database_service
    ports:
      - "27017:27017"
    networks:
      - inventory_network

networks:
  inventory_network: